### ISSUE TITLE
Can't send payment

### ISSUE THREAD

**Issue by brian7989** [mmohades/VenmoApiDocumentation#10]
The /payments endpoint doesn't seem to be working.
The response status is 200, but it still won't send a payment.

**Comment by collindutter** [comment]
@brian7989 I get a 500 error when I try to use /payments. Every other endpoint works fine.

**Comment by mmohades** [comment]
I think there might have been a change in the API schema. Can you try sending the `user_id` as a string instead of an int?
``` 
{
....,
"user_id": "4696228937479104362",
....
}
```

**Comment by jakevo** [comment]
> I think there might have been a change in the API schema. Can you try sending the `user_id` as a string instead of an int?
> 
> ```
> {
> ....,
> "user_id": "4696228937479104362",
> ....
> }
> ```

it works thank you
