### ISSUE TITLE
400 Using login endpoint

### ISSUE THREAD

**Issue by tiludropdancer** [mmohades/VenmoApiDocumentation#8]
I followed the request structure as specified to send a text with the venmo otp, however when sending a request to
```POST https://api.venmo.com/v1/oauth/access_token?client_id=1```

I see:
```
{
    "error": {
        "message": "Your code has expired. Sign in again and we'll send you a new code.",
        "code": 81110,
        "links": null,
        "title": "Error"
    }
}
```

Is there an error in the documentation?

**Comment by mmohades** [comment]
The authentication process should happen quickly, otherwise the `otp-sercret` or the `otp` will expire. Here either your `otp` has expired or `otp-sercret`

**Comment by tiludropdancer** [comment]
The issue was a problem in postman. The request returns 200 now.
